In [3]:
!pip install biopython pandas

Requirement already satisfied: biopython in C:\Users\rajdeep\OneDrive\Desktop\protein-function-prediction\venv\Lib\site-packages (1.87)
Requirement already satisfied: pandas in C:\Users\rajdeep\OneDrive\Desktop\protein-function-prediction\venv\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy in C:\Users\rajdeep\OneDrive\Desktop\protein-function-prediction\venv\Lib\site-packages (from biopython) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\rajdeep\OneDrive\Desktop\protein-function-prediction\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\rajdeep\OneDrive\Desktop\protein-function-prediction\venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\rajdeep\OneDrive\Desktop\protein-function-prediction\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
from Bio import SeqIO

file_path = "../dataset/uniprot_sprot.fasta/uniprot_sprot.fasta"

records = list(SeqIO.parse(file_path, "fasta"))

print("Total sequences:", len(records))
print(records[0])

Total sequences: 574627
ID: sp|Q6GZX4|001R_FRG3G
Name: sp|Q6GZX4|001R_FRG3G
Description: sp|Q6GZX4|001R_FRG3G Putative transcription factor 001R OS=Frog virus 3 (isolate Goorha) OX=654924 GN=FV3-001R PE=4 SV=1
Number of features: 0
Seq('MAFSAEDVLKEYDRRRRMEALLLSLYYPNDRKLLDYKEWSPPRVQVECPKAPVE...TPL')

In [5]:
import pandas as pd

data = []

for record in records:
    sequence = str(record.seq)
    description = record.description.lower()
    
    if "enzyme" in description or "kinase" in description or "transferase" in description:
        label = "enzyme"
    elif "binding" in description:
        label = "binding"
    elif "transport" in description:
        label = "transport"
    else:
        label = "other"
    
    data.append([sequence, label])

df = pd.DataFrame(data, columns=["sequence", "label"])

df.head()

                                            sequence  label
0  MAFSAEDVLKEYDRRRRMEALLLSLYYPNDRKLLDYKEWSPPRVQV...  other
1  MSIIGATRLQNDKSDTYSAGPCYAGGCSAFTPRGTCGKDWDLGEQT...  other
2  MASNTVSAQGGSNRPVRDFSNIQDVAQFLLFDPIWNEQPGSIVPWK...  other
3  MYQAINPCPQSWYGSPQLEREIVCKMSGAPHYPNYYPVHPNALGGA...  other
4  MARPLLGKTSSVRRRLESLSACSIFFFLRKFCQKMASLVFLNSPVY...  other

In [6]:
df["label"].value_counts()

label
other        474907
enzyme        76678
binding       15112
transport      7930
Name: count, dtype: int64

In [7]:
df.to_csv("../dataset/protein_data.csv", index=False)

In [8]:
df = df[df["label"] != "other"]
df["label"].value_counts()

label
enzyme       76678
binding      15112
transport     7930
Name: count, dtype: int64

In [9]:
min_count = df["label"].value_counts().min()

df_balanced = df.groupby("label").sample(n=min_count, random_state=42)

df_balanced["label"].value_counts()

label
binding      7930
enzyme       7930
transport    7930
Name: count, dtype: int64

In [10]:
df_balanced.to_csv("../dataset/protein_balanced.csv", index=False)

In [11]:
import pandas as pd

df = pd.read_csv("../dataset/protein_balanced.csv")

df.head()

                                            sequence    label
0  MSDQFNSREARRKANSKSSPSPKKGKKRKKGGLFKKTLFTLLILFV...  binding
1  MSEPLLHLTGISRSFTAGDREFLALKHIDLSIQAGEMVAITGASGS...  binding
2  MKVNPNNIELIISAVKEEQYPETELSEVALSGRSNVGKSTFINSMI...  binding
3  MARYDLVDRLNTTFRQMEQELAAFAAHLEQHKLLVARVFSLPEVKK...  binding
4  MFWGIEISKVPVKFTPAFDLHITTACLSAVAKDTGRNVLQVKYDGK...  binding

In [12]:
def kmer_sequence(seq, k=3):
    return " ".join([seq[i:i+k] for i in range(len(seq)-k+1)])

df["kmer"] = df["sequence"].apply(lambda x: kmer_sequence(x, k=3))

df.head()

,sequence,label,kmer
0,MSDQFNSREARRKANSKSSPSPKKGKKRKKGGLFKKTLFTLLILFV...,binding,MSD SDQ DQF QFN FNS NSR SRE REA EAR ARR RRK RK...
1,MSEPLLHLTGISRSFTAGDREFLALKHIDLSIQAGEMVAITGASGS...,binding,MSE SEP EPL PLL LLH LHL HLT LTG TGI GIS ISR SR...
2,MKVNPNNIELIISAVKEEQYPETELSEVALSGRSNVGKSTFINSMI...,binding,MKV KVN VNP NPN PNN NNI NIE IEL ELI LII IIS IS...
3,MARYDLVDRLNTTFRQMEQELAAFAAHLEQHKLLVARVFSLPEVKK...,binding,MAR ARY RYD YDL DLV LVD VDR DRL RLN LNT NTT TT...
4,MFWGIEISKVPVKFTPAFDLHITTACLSAVAKDTGRNVLQVKYDGK...,binding,MFW FWG WGI GIE IEI EIS ISK SKV KVP VPV PVK VK...

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(df["kmer"])
y = df["label"]

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [15]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

     binding       0.86      0.91      0.88      1563
      enzyme       0.88      0.86      0.87      1573
   transport       0.93      0.91      0.92      1622

    accuracy                           0.89      4758
   macro avg       0.89      0.89      0.89      4758
weighted avg       0.89      0.89      0.89      4758

In [16]:
print(X.shape)

(23790, 8189)

In [ ]:
print(y.shape)

# Model Improvements

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(df["kmer"])

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_tfidf, y, test_size=0.2, random_state=42)

In [20]:
from sklearn.linear_model import LogisticRegression

model_lr = LogisticRegression(max_iter=1000)
model_lr.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [21]:
from sklearn.metrics import classification_report

y_pred = model_lr.predict(X_test)
print("TF-IDF + Logistic Regression")
print(classification_report(y_test, y_pred))

TF-IDF + Logistic Regression
              precision    recall  f1-score   support

     binding       0.89      0.90      0.89      1563
      enzyme       0.87      0.89      0.88      1573
   transport       0.94      0.91      0.93      1622

    accuracy                           0.90      4758
   macro avg       0.90      0.90      0.90      4758
weighted avg       0.90      0.90      0.90      4758

In [22]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(n_estimators=100)
model_rf.fit(X_train, y_train)

y_pred_rf = model_rf.predict(X_test)

print("Random Forest")
print(classification_report(y_test, y_pred_rf))

Random Forest
              precision    recall  f1-score   support

     binding       0.94      0.84      0.89      1563
      enzyme       0.81      0.90      0.86      1573
   transport       0.91      0.91      0.91      1622

    accuracy                           0.88      4758
   macro avg       0.89      0.88      0.88      4758
weighted avg       0.89      0.88      0.88      4758

In [23]:
from sklearn.svm import LinearSVC

model_svm = LinearSVC()
model_svm.fit(X_train, y_train)

y_pred_svm = model_svm.predict(X_test)

print("SVM")
print(classification_report(y_test, y_pred_svm))

SVM
              precision    recall  f1-score   support

     binding       0.89      0.92      0.90      1563
      enzyme       0.90      0.88      0.89      1573
   transport       0.94      0.93      0.94      1622

    accuracy                           0.91      4758
   macro avg       0.91      0.91      0.91      4758
weighted avg       0.91      0.91      0.91      4758

In [24]:
import joblib

joblib.dump(model_svm, "../models/best_model.pkl")
joblib.dump(tfidf, "../models/vectorizer.pkl")

['../models/vectorizer.pkl']

In [25]:
def predict_protein(sequence):
    # convert to k-mer
    kmer_seq = " ".join([sequence[i:i+3] for i in range(len(sequence)-2)])
    
    # transform using saved vectorizer
    X_input = tfidf.transform([kmer_seq])
    
    # predict
    prediction = model_svm.predict(X_input)[0]
    
    return prediction

In [31]:
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import classification_report

base_svm = LinearSVC()

model_svm_prob = CalibratedClassifierCV(base_svm, cv=3)

model_svm_prob.fit(X_train, y_train)

y_pred = model_svm_prob.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

     binding       0.90      0.92      0.91      1563
      enzyme       0.90      0.89      0.89      1573
   transport       0.94      0.93      0.94      1622

    accuracy                           0.91      4758
   macro avg       0.91      0.91      0.91      4758
weighted avg       0.91      0.91      0.91      4758

In [32]:
def predict_protein_with_confidence(sequence):
    kmer_seq = " ".join([sequence[i:i+3] for i in range(len(sequence)-2)])
    
    X_input = tfidf.transform([kmer_seq])
    
    prediction = model_svm_prob.predict(X_input)[0]
    
    probabilities = model_svm_prob.predict_proba(X_input)[0]
    confidence = max(probabilities) * 100
    
    return prediction, round(confidence, 2)

In [33]:
test_seq = df["sequence"].iloc[0]

prediction, confidence = predict_protein_with_confidence(test_seq)

print("Prediction:", prediction)
print("Confidence:", confidence, "%")

Prediction: binding
Confidence: 91.72 %

In [34]:
import joblib

joblib.dump(model_svm_prob, "../models/best_model_with_confidence.pkl")
joblib.dump(tfidf, "../models/vectorizer.pkl")

['../models/vectorizer.pkl']

In [46]:
new_seq = "KELD"

prediction, confidence = predict_protein_with_confidence(new_seq)

print("Prediction:", prediction)
print("Confidence:", confidence, "%")

Prediction: binding
Confidence: 86.07 %

In [48]:
new_seq = "MGLSDGEWQLVLNVWGKVEADIPGHGQEVLIRLFKSHPETLEKFDRFKHLKTEAEMKASEDLKKHGATVLTALGGILKKKGHHEAEIKPLAQSHATKHKIPVKYLEFISEAIIHVLHSRHPGDFGADAQGAMNKALELFRKDIAAKYKELGFQG"

prediction, confidence = predict_protein_with_confidence(new_seq)

print(prediction, confidence)

binding 70.66

In [49]:
from sklearn.metrics import accuracy_score, f1_score

results = []

models = {
    "TF-IDF + Logistic Regression": model_lr,
    "TF-IDF + Random Forest": model_rf,
    "TF-IDF + SVM": model_svm,
    "TF-IDF + SVM with Confidence": model_svm_prob
}

for name, m in models.items():
    pred = m.predict(X_test)
    acc = accuracy_score(y_test, pred)
    f1 = f1_score(y_test, pred, average="weighted")
    
    results.append([name, acc, f1])

results_df = pd.DataFrame(results, columns=["Model", "Accuracy", "Weighted F1"])
results_df

                          Model  Accuracy  Weighted F1
0  TF-IDF + Logistic Regression  0.901009     0.901180
1        TF-IDF + Random Forest  0.883144     0.883699
2                  TF-IDF + SVM  0.911517     0.911535
3  TF-IDF + SVM with Confidence  0.911728     0.911783

In [50]:
import joblib

joblib.dump(model_svm_prob, "../models/final_protein_model.pkl")
joblib.dump(tfidf, "../models/final_vectorizer.pkl")

['../models/final_vectorizer.pkl']

In [51]:
def predict_protein_function(sequence):
    sequence = sequence.upper().replace(" ", "").replace("\n", "")
    
    kmer_seq = " ".join([sequence[i:i+3] for i in range(len(sequence)-2)])
    X_input = tfidf.transform([kmer_seq])
    
    prediction = model_svm_prob.predict(X_input)[0]
    probabilities = model_svm_prob.predict_proba(X_input)[0]
    confidence = max(probabilities) * 100
    
    return prediction, round(confidence, 2)

sample_seq = df["sequence"].sample(1).values[0]

pred, conf = predict_protein_function(sample_seq)

print("Prediction:", pred)
print("Confidence:", conf, "%")

Prediction: enzyme
Confidence: 92.09 %